<div id=footer>
 			
 			<table class="foot">
 				<tr class="foot_tr">
				    <th class="foot_th">Punjabi Feast</th>
				    <th class="foot_th">Punjabi Feast</th>
				    <th class="foot_th">Our Location</th>
				    <th class="foot_th">Working Hours</th>
				</tr>
				<tr class="foot_tr">
					<td class="foot_td">
						<ul class="foot_menu">
							<li class="foot_menu_list"><a href="index.php">Home</a></li>
							<li class="foot_menu_list"><a href="about.php">About</a></li>
 							<li class="foot_menu_list"><a href="menu.php">Menu</a></li>
							<li class="foot_menu_list"><a href="enquiry.php">Enquiry</a></li>
							<li class="foot_menu_list"><a href="contact.php">Contact Us</a></li>
						</ul>

					</td>
					<td class="foot_td">
						<ul class="foot_menu">
							<li class="foot_menu_list"><a href="meal_packages.php">Meal Packages</a></li>
							<li class="foot_menu_list"><a href="nutrition_chart.php">Nutrition Chart</a></li>
							<li class="foot_menu_list"><a href="help_homeless.php">Help Homeless</a></li>
 							<li class="foot_menu_list"><a href="refund_policy.php">Refund Policy</a></li>
							<li class="foot_menu_list"><a href="career.php">Careers</a></li>
						</ul>

					</td>
					<td class="foot_td">
						<ul class="foot_menu">
							<li class="foot_menu_list">13724, Grosvenor Rd</li>
							<li class="foot_menu_list">V3R5E4, Surrey</li>
 							<li class="foot_menu_list">British Columbia</li>
							<li class="foot_menu_list">+1 604-773-0453</li>
						</ul>

					</td>
					<td class="foot_td">
						<ul class="foot_menu">
							<li class="foot_menu_list">Mon-Fri</li>
							<li class="foot_menu_list">09:00 AM-06:00 PM</li>
 							<li class="foot_menu_list">Sat-Sun & Holidays</li>
							<li class="foot_menu_list">11:00 AM-04:00 PM </li>
<!-- 							<li class="foot_menu_list">@gmail.com</li> -->
						</ul>
					</td>
				</tr>
  
 			</table>
 			<a class="black_bg" href="index.php"><img id="logo_1" src="images/logo_name.png" alt="Punjabi Feast"></a>
 			
 		</div>